version: "3.8"
services:
  backend:
    image: "asadkomi/spring-react-soccerplayer:11.9.2021.18.56.30"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev

