version: "3.8"
services:
  backend:
    image: "asadkomi/spring-react-soccerplayer:6.9.2021.14.35.18"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev

